inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
  - 'lib/rap_sheet_parser/syntax_nodes/treetop_monkeypatches.rb'

Metrics/AbcSize:
  Exclude:
  - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*'

Metrics/ModuleLength:
  Exclude:
  - 'spec/**/*'

Style/Documentation:
  Enabled: false
