inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
  - 'lib/rap_sheet_parser/syntax_nodes/treetop_monkeypatches.rb'

Metrics/AbcSize:
  Exclude:
  - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*'
  - 'rap_sheet_parser.gemspec'

Metrics/ModuleLength:
  Exclude:
  - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
  - 'lib/rap_sheet_parser/builders/courthouse_builder.rb'

Metrics/ClassLength:
  Exclude:
  - 'lib/rap_sheet_parser/builders/courthouse_builder.rb'

Style/Documentation:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Naming/PredicateName:
  NamePrefix: ['is_']
