module RapSheetParser
  class CourthouseBuilder
    def initialize(courthouse_node, logger:)
      @courthouse_node = courthouse_node
      @logger = logger
    end

    def build
      courthouse_names = {
        'CAJC HOLLISTER' => 'CAJC Hollister',
        'CAJC MADERA' => 'CAJC Madera',
        'CAJC SANGER' => 'CAJC Sanger',
        'CAJV ALAMEDA' => 'CAJV Alameda',
        'CAJV CONTRA COSTA EAST DIV' => 'CAJV Contra Costa East Div',
        'CAJV SACRAMENTO' => 'CAJV Sacramento',
        'CAJV SAN FRANCISCO CO' => 'CAJV San Francisco Co',
        'CAJV SAN MATEO JUV' => 'CAJV San Mateo Juv',
        'CAJV SF JUV DELINQUENCY' => 'CAJV SF Juv Delinquency',
        'CAJV SN FRANCISCO CO' => 'CAJV San Francisco',
        'CAJV WEST CONTRA COSTA CO' => 'CAJV West Contra Costa Co',
        'CAMC ALAMEDA' => 'CAMC Alameda',
        'CAMC BAKERSFIELD' => 'CAMC Bakersfield',
        'CAMC BARSTOW' => 'CAMC Barstow',
        'CAMC BERKELEY' => 'CAMC Berkeley',
        'CAMC BEVERLY HILLS' => 'CAMC Beverly Hills',
        'CAMC CALEXICO DEPT' => 'CAMC Calexico Dept',
        'CAMC COMPTON' => 'CAMC Compton',
        'CAMC CONCORD' => 'CAMC Concord',
        'CAMC CULVER CITY' => 'CAMC Culver City',
        'CAMC EL MONTE' => 'CAMC El Monte',
        'CAMC FONTANA' => 'CAMC Fontana',
        'CAMC FREMONT' => 'CAMC Fremont',
        'CAMC FRESNO' => 'CAMC Fresno',
        'CAMC GLENDALE' => 'CAMC Glendale',
        'CAMC HAYWARD' => 'CAMC Hayward',
        'CAMC HOLLYWOOD' => 'CAMC Hollywood',
        'CAMC LIVERMORE' => 'CAMC Livermore',
        'CAMC LODI' => 'CAMC Lodi',
        'CAMC LONG BEACH' => 'CAMC Long Beach',
        'CAMC LOS ANGELES METRO' => 'CAMC Los Angeles Metro',
        'CAMC MODESTO' => 'CAMC Modesto',
        'CAMC MOJAVE' => 'CAMC Mojave',
        'CAMC MONTEREY' => 'CAMC Monterey',
        'CAMC OAKLAND' => 'CAMC Oakland',
        'CAMC REDDING' => 'CAMC Redding',
        'CAMC REDWOOD CITY' => 'CAMC Redwood City',
        'CAMC RICHMOND' => 'CAMC Richmond',
        'CAMC SALINAS' => 'CAMC Salinas',
        'CAMC SAN DIEGO' => 'CAMC San Diego',
        'CAMC SAN FERNANDO' => 'CAMC San Fernando',
        'CAMC SAN FRANCISCO' => 'CAMC San Francisco',
        'CAMC SAN JOSE' => 'CAMC San Jose',
        'CAMC SAN LUIS OBISPO' => 'CAMC San Luis Obsipo',
        'CAMC SAN RAFAEL' => 'CAMC San Rafael',
        'CAMC SANTA ANA' => 'CAMC Santa Ana',
        'CAMC SANTA BARBARA' => 'CAMC Santa Barbara',
        'CAMC SANTA CRUZ' => 'CAMC Santa Cruz',
        'CAMC SANTA MONICA' => 'CAMC Santa Monica',
        'CAMC SANTA ROSA' => 'CAMC Santa Rosa',
        'CAMC SOUTH SAN FRANCISCO' => 'CAMC South San Francisco',
        'CAMC STOCKTON' => 'CAMC Stockton',
        'CAMC SUNNYVALE' => 'CAMC Sunnyvale',
        'CAMC TAFT' => 'CAMC Taft',
        'CAMC VALLEJO' => 'CAMC Vallejo',
        'CAMC VAN NUYS' => 'CAMC Van Nuys',
        'CAMC VENTURA' => 'CAMC Ventura',
        'CAMC VISTA' => 'CAMC Vista',
        'CAMC WALNUT CREEK' => 'CAMC Walnut Creek',
        'CAMC WESTMINSTER' => 'CAMC Westminster',
        'CAMC WOODLAND' => 'CAMC Woodland',
        'CASC ALHAMBRA' => 'CASC Alhambra',
        'CASC BAKERSFIELD' => 'CASC Bakersfield',
        'CASC BERKELEY' => 'CASC Berkeley',
        'CASC BEVERLY HILLS' => 'CASC Beverly Hills',
        'CASC BUTTE' => 'CASC Butte',
        'CASC CALAVERAS' => 'CASC Calaveras',
        'CASC CHICO' => 'CASC Chico',
        'CASC CONCORD' => 'CASC Concord',
        'CASC CONTRA COSTA CO' => 'CASC Contra Costa Co',
        'CASC CONTRA COSTA' => 'CASC Contra Costa',
        'CASC DEL NORT E' => 'CASC Del Norte',
        'CASC DEL NORTE' => 'CASC Del Norte',
        'CASC EAST LOS ANGELES' => 'CASC East Los Angeles',
        'CASC EL CENTRO' => 'CASC El Centro',
        'CASC EL MONTE' => 'CASC El Monte',
        'CASC FAIRFIEL D' => 'CASC Fairfield',
        'CASC FAIRFIELD' => 'CASC Fairfield',
        'CASC FORT BRAGG' => 'CASC Fort Bragg',
        'CASC FREMONT' => 'CASC Fremont',
        'CASC FRESNO CENTRAL' => 'CASC Fresno Central',
        'CASC FRESNO' => 'CASC Fresno',
        'CASC FULLERTON' => 'CASC Fullerton',
        'CASC GILROY' => 'CASC Gilroy',
        'CASC GLENDALE' => 'CASC Glendale',
        'CASC HUMBOLDT' => 'CASC Humboldt',
        'CASC INDIO' => 'CASC Indio',
        'CASC LAKE' => 'CASC Lake',
        'CASC LANCASTER' => 'CASC Lancaster',
        'CASC LIVERMORE' => 'CASC Livermore',
        'CASC LODI' => 'CASC Lodi',
        'CASC LONG BEACH' => 'CASC Long Beach',
        'CASC LOS ANGELES CENTRAL' => 'CASC Los Angeles Central',
        'CASC LOS ANGELES METRO' => 'CASC Los Angeles Metro',
        'CASC LOS ANGELES POMONA' => 'CASC los Angeles Pomona',
        'CASC LOS ANGELES' => 'CASC Los Angeles',
        'CASC MADERA' => 'CASC Madera',
        'CASC MCCHULA VISTA' => 'CASC MC Chula Vista',
        'CASC MCHAYWARD' => 'CASC MC Hayward',
        'CASC MCMERCED' => 'CASC MC Merced',
        'CASC MCOAKLAND' => 'CASC MC Oakland',
        'CASC MCPALO ALTO' => 'CASC MC Palo Alto',
        'CASC MCRICHMOND' => 'CASC Richmond',
        'CASC MCSACRAMENTO' => 'CASC MC Sacramento',
        'CASC MCSAN LUIS OBISPO' => 'CASC MC San Luis Obispo',
        'CASC MCSAN RAFAEL' => 'CASC MC San Rafael',
        'CASC MCVAN NUYS' => 'CASC MC Van Nuys',
        'CASC MCVENTURA' => 'CASC MC Ventura',
        'CASC MCVICTORVILLE' => 'CASC MC Victorville',
        'CASC MENDOCINO' => 'CASC Mendocino',
        'CASC MERCED' => 'CASC Merced',
        'CASC MONTEREY' => 'CASC Monterey',
        'CASC NAPA' => 'CASC Napa',
        'CASC NEVADA CITY' => 'CASC Nevada City',
        'CASC NEVADA' => 'CASC Nevada',
        'CASC NEWPORT BEACH' => 'CASC Newport Beach',
        'CASC OAKLAND' => 'CASC Oakland',
        'CASC PITTSBURG' => 'CASC Pittsburg',
        'CASC PLACER' => 'CASC Placer',
        'CASC PLUMAS' => 'CASC Plumas',
        'CASC POMONA' => 'CASC Pomona',
        'CASC QUINCY' => 'CASC Quincy',
        'CASC REDWOOD CITY' => 'CASC Redwood City',
        'CASC SACRAMENTO' => 'CASC Sacramento',
        'CASC SAN DIEGO CENTRAL' => 'CASC San Diego Central',
        'CASC SAN DIEGO' => 'CASC San Diego',
        'CASC SAN FERNANDO' => 'CASC San Fernando',
        'CASC SAN FRANCISCO CO' => 'CASC San Francisco Co',
        'CASC SAN FRANCISCO' => 'CASC San Francisco',
        'CASC SAN MATEO' => 'CASC San Mateo',
        'CASC SANTA ANA' => 'CASC Santa Ana',
        'CASC SANTA BARBARA' => 'CASC Santa Barbara',
        'CASC SANTA CLARA' => 'CASC Santa Clara',
        'CASC SANTA CRUZ CRIM TRAFF' => 'CASC Santa Cruz Crim Traff',
        'CASC SANTA CRUZ' => 'CASC Santa Cruz',
        'CASC SANTA MONICA' => 'CASC Santa Monica',
        'CASC SANTA ROSA' => 'CASC Santa Rosa',
        'CASC SHASTA' => 'CASC Shasta',
        'CASC SN JOSE' => 'CASC San Jose',
        'CASC SNTA BARBARA' => 'CASC Santa Barbara',
        'CASC SNTA MARIA' => 'CASC Santa Maria',
        'CASC SOLANO' => 'CASC Solano',
        'CASC SONOMA' => 'CASC Sonoma',
        'CASC SOUTH LAKE TAHOE' => 'CASC South Lake Tahoe',
        'CASC SOUTH SAN FRANCISCO' => 'CASC South San Francisco',
        'CASC STANISLAUS' => 'CASC Stanislaus',
        'CASC STOCKTON' => 'CASC Stockton',
        'CASC SUNNYVALE' => 'CASC Sunnyvale',
        'CASC SUSANVILLE' => 'CASC Susanville',
        'CASC TEHAMA' => 'CASC Tehama',
        'CASC TRACY' => 'CASC Tracy',
        'CASC TRINITY' => 'CASC Trinity',
        'CASC TRUCKEE' => 'CASC Truckee',
        'CASC TULARE' => 'CASC Tulare',
        'CASC TUOLUMNE' => 'CASC Tuolumne',
        'CASC UKIAH' => 'CASC Ukiah',
        'CASC VALLEJO' => 'CASC Vallejo',
        'CASC VENTURA' => 'CASC Ventura',
        'CASC VISTA BRANCH' => 'CASC Vista Branch',
        'CASC VISTA' => 'CASC Vista',
        'CASC WALNUT CREEK' => 'CASC Walnut Creek',
        'CASC WEST COVINA' => 'CASC West Covina',
        'CASC WEST LA AIRPORT' => 'CASC West LA Airport',
        'CASC WEST LOS ANGELES' => 'CASC West Los Angeles',
        'CASC WESTMINSTER' => 'CASC Westminster',
        'CASC WILLITS' => 'CASC Willits',
        'CASC WOODLAND' => 'CASC Woodland',
        'CASC YOLO' => 'CASC Yolo',
        'CASC YUBA CITY' => 'CASC Yuba City',
        'CASC YUBA' => 'CASC Yuba'
      }

      courthouse_text = @courthouse_node.text_value.delete('.').upcase

      if courthouse_names.key?(courthouse_text)
        courthouse_names[courthouse_text]
      else
        @logger.warn('Unrecognized courthouse:')
        @logger.warn(courthouse_text)

        courthouse_text
      end
    end
  end
end
